#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.
password="$1"
mysqldump -u root -p"$password" --all-databases > backup.sql
tar czvf "$(date +%d-%m-%Y).tar.gz" backup.sql
