#!/usr/bin/env bash
# Configures container to run Nginx as nginx user
pkill apache2
sed -i 's/\b80\b/&80/' /etc/nginx/sites-available/default
chmod 755 /etc/nginx/nginx.conf
sudo -u nginx bash -c 'service nginx restart'
